### ISSUE TITLE
[Bug] Issue importing settings from grid

### ISSUE THREAD

**Issue by Voxxel** [doadin/Plexus#22]
**Describe the bug**
Very bad bug on EU realms after successfully copying settings from Grid.

**To Reproduce**
1. start wow.exe
2. Get into party with russian ppl
3. Set your eyes on their names

**Expected behavior**
grid 

**Screenshots**
https://i.imgur.com/DE6DYbP.jpg

**Desktop (please complete the following information):**
 - OS: windows
 - Version latest
 - Game Version 9.x prepatch

**Additional context**

**Comment by doadin** [comment]
This is due to an issue with font the default font doesn't support rus characters try one of the following fonts: 2002, AR ZhongkaiGBK Medium,  MoK. ref: https://www.curseforge.com/wow/addons/plexus?comment=321 . From the game it sets a default font that is client appropriate, except when you factor people from different countries playing on different locations with different clients language settings. I am considering changing what plexus uses as default font.

**Comment by doadin** [comment]
https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/Fonts.xml STANDARD_TEXT_FONT is what plexus uses.

**Comment by doadin** [comment]
Did font solve your issue or no?

**Comment by doadin** [comment]
closing as im assuming its Duplicate: https://github.com/doadin/Plexus/issues/25#issuecomment-720117661

**Comment by Voxxel** [comment]
I of course know this is a font issue, but copying settings from Grid should copy the used font too. It would be better and less confusing to users, I believe.

**Comment by doadin** [comment]
ok reopened, fixed title. ill look into it.

**Comment by doadin** [comment]
fixed: fe21286005b351b2d9c18ce9c3958668aefdcdd4
