### ISSUE TITLE
[Bug] Normal form don't show the energybar

### ISSUE THREAD

**Issue by Sekorhex** [doadin/Plexus#37]
**Describe the bug**
When i switch from the Cat form to the normal form it shows the energybar. I test it with the bear form and that works perfectly, but only the Cat Form made this problem.

**To Reproduce**
1. Go to Cat Form
2. Get out of the Cat Form
3. Look Ressourcebar (Its the Energybar)

**Expected behavior**
When i'm going ot of stance then it must show the manabar.

**Screenshots**
![wtf](https://user-images.githubusercontent.com/42946288/101280270-745a6480-37c8-11eb-8d41-3bb135c1e1d3.PNG)

Desktop (please complete the following information):

  - OS: Windows 10
  - Version 20H2
  - Game Version: Retail 9.0.2

**Comment by doadin** [comment]
This is due to resource value not changing/unit resoruce event not firing from the game when chaning forms, the second any of the unit resources change it should change however, hopefully bbad63db03583185c52655f09dbe6fe7ef94557d will fix this by updating the resource when auras change which druid forms do apply an aura so should trigger. This commit should be released soon.
