### ISSUE TITLE
[Bug] Text Indicator is not in the right place

### ISSUE THREAD

**Issue by Sekorhex** [doadin/Plexus#42]
I really love your addon but i have some issues about Plexus Dynamic Indicators. I create a Text Indicator for names. When i'm in a dungeon group then it shows correctly the names

**Describe the bug**
Text indicator like names don't have a correct position. In Dungeon Group is that ok but on higher group the names looks like on screenshots

**To Reproduce**
1. Go to '/plexus'
2. Click on 'Dynamic Indicators'
3. Create 'Text Indicator'

**Expected behavior**
I want the names into the bars not over the bars.

**Screenshots**
![Screenshot_5](https://user-images.githubusercontent.com/42946288/106645414-9b48d300-658c-11eb-8df8-d171f7e0088a.png)

![Screenshot_6](https://user-images.githubusercontent.com/42946288/106645517-c16e7300-658c-11eb-9229-453bb6167dc1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version: 20H2
 - Game Version: Retail 9.0.2

**Additional context**

**Comment by doadin** [comment]
What are your frame sizes?

**Comment by Sekorhex** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/42946288/106910614-b38e2e80-6701-11eb-8a30-62f4da238711.png)
![Screenshot_3](https://user-images.githubusercontent.com/42946288/106910631-b5f08880-6701-11eb-8f69-3bfcf9b1253f.png)

**Comment by doadin** [comment]
ok so that looks about right to me, if your frames are only 25 pixels high and you have the indicator set to be 23 pixels up from the center, its going to go out of frame. The part maybe you missed is that its anchoring from center not bottom. though this is one down fall of auto size is that it maybe be hard to find placement that fits all sizes. I would maybe suggest, for the indicator anchor from top and use -5 for y, That way no matter how stretched your frame is it will always be close to the top.

**Comment by Sekorhex** [comment]
allright thank you i will change it.

**Comment by doadin** [comment]
ok, im going to go ahead and close this if you still have this issue or another please reopen or open a new issue, thanks!
