### ISSUE TITLE
[Bug] can't set icon in plexus

### ISSUE THREAD

**Issue by haishui598** [doadin/Plexus#95]
Plexus used to work fine in the Chinese Wlk nostalgic server represented by NetEase. After more than a year of suspension of service, after Wlk was reopened in China this year, Plexus cannot set icons. All settings are correct, but it just doesn't work. This is a common problem. Due to this problem, Plexus is almost impossible to use on Chinese Wlk servers, unless you don't plan to monitor any icons.

**Comment by doadin** [comment]
Are you getting any errors? I have just now tested the aura code for all 3 available US versions of the game and it works fine, this issue must be related to wrath specifically. I would like to update however I don't think I can access the Chinese servers.

**Comment by doadin** [comment]
I have attempted to make a guess that since everything else works but the auras just don't show up, that this is an issue with the aura scanning/tracking code and wrath was not updated to the new style. I have pushed this commit ( 0e7c9115b1bb0486de46d95cce33642570b7bdfb ) which is included in v3.2.3. Please let me know if this fixes this. Thanks!

**Comment by haishui598** [comment]
it work now in v3.2.3,thank u very much
